run:
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - dupl
    - exportloopref
    - gocyclo
    - godox
    - gofmt
    - goimports
    - golint
    - govet
    - misspell
    - prealloc
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - deadcode # Disabled during early devellopment
    - errcheck
    - gosec # Disabled during early devellopment
    - structcheck # Disabled during early devellopment
    - unused # Disabled during early devellopment
    - varcheck # Disabled during early devellopment